
using System.Windows.Forms;

namespace WatermarkScreen
{
    partial class Watermark
    {
        /// <summary>
        /// Variável de designer necessária.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Limpar os recursos que estão sendo usados.
        /// </summary>
        /// <param name="disposing">true se for necessário descartar os recursos gerenciados; caso contrário, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by Windows Form Designer

        /// <summary>
        /// Método necessário para suporte ao Designer - não modifique 
        /// o conteúdo deste método com o editor de código.
        /// </summary>
        private void InitializeComponent()
        {
            this.SuspendLayout();
            // 
            // Watermark Constructor 
            // 

            this.AutoScaleDimensions = new System.Drawing.SizeF(13F, 29F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Gray;
            this.ClientSize = new System.Drawing.Size(259, 111);

            //I used a Monospace Font to remove the reposition measure that happens when use a proportional font.
            this.Font = new System.Drawing.Font("Consolas", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);

            //Specifies the dimensions of the margins of a printed page.
            this.Margin = new System.Windows.Forms.Padding(7);
            this.MaximizeBox = false;
            this.MinimizeBox = false;

            //Define the name of Controler
            this.Name = "Watermark";

            //Sets the form's opacity level.
            this.Opacity = .15;

            //Indicates whether a window appears in front of the others.
            this.TopMost = true;

            //Sets a value that indicates whether form is maximized.
            this.WindowState = FormWindowState.Maximized;

            this.Paint += Watermark_Paint;
            this.SetStyle(ControlStyles.AllPaintingInWmPaint | ControlStyles.UserPaint | ControlStyles.OptimizedDoubleBuffer | ControlStyles.DoubleBuffer, true );
            //this.FormBorderStyle = FormBorderStyle.SizableToolWindow;
            this.FormBorderStyle = FormBorderStyle.None;
            this.ShowInTaskbar = false;
            this.TopMost = true;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.TransparencyKey = System.Drawing.Color.Gray;
            this.WindowState = FormWindowState.Maximized;

            //Gets or sets the coordinates of the upper-left corner of the control relative to the upper-left corner of its container.
            this.Location = Screen.AllScreens[1].WorkingArea.Location;

            //Occurs before the control becomes visible for the first time.
            this.Load += new System.EventHandler(this.Watermark_Load);

            //Timer Implementation like Component
            System.Windows.Forms.Timer aTimer = new System.Windows.Forms.Timer();
            aTimer.Interval = 1000; // In 1000 milliseconds the timer will update
            aTimer.Enabled = true;
            ///
            ///<summary> Ocorre quando o intervalo especificado tiver terminado e o temporizador estiver habilitado. </summary>
            ///<see href="https://docs.microsoft.com/pt-br/dotnet/api/system.windows.forms.timer?view=windowsdesktop-6.0"> </see>>
            ///

            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
    }
}

